replicaCount: 1

datagrid:
  name: globex-datagrid

cache:
  name: default
  template:
    distributedCache: 
      owners: "2"
      mode: "SYNC"
      statistics: "true"
      memory: 
        storage: "OFF_HEAP"
        maxSize: "633339904"
        whenFull: "REMOVE"
      partitionHandling: 
        whenSplit: "ALLOW_READ_WRITES"
        mergePolicy: "REMOVE_ALL"
  updates:
    strategy: retain

truststore:
  name: client-infinispan.ts

identities:
  username: developer
  password: password

hook:
  image:
    repository: quay.io/cloud-architecture-workshop/datagrid-truststore-secret-job
    pullPolicy: IfNotPresent
    tag: "91f641f-native"
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  argocd:
    enabled: true
    syncwave: "1"
